import assert from "node:assert/strict";
import { query } from "./registry-ci-store.js";
import { NeonRegistryStore } from "../src/admin/registry-store.js";
import { applyRegistryCommand } from "../src/admin/registry.js";
const first = new NeonRegistryStore(query);
const initial = await first.read();
const next = applyRegistryCommand(initial.data, { action: "add_customer", name: "SQL regression 'example'", slug: "sql-regression" }, "ci-regression");
const result = await first.write(initial.version, next);
const reconnected = new NeonRegistryStore(query);
assert.deepEqual(await reconnected.read(), result, "A fresh store reads the same persisted record");
const races = await Promise.allSettled([first.write(result.version, next), reconnected.write(result.version, next)]);
assert.equal(races.filter(r => r.status === "fulfilled").length, 1);
assert.equal(races.filter(r => r.status === "rejected").length, 1);
assert.equal((await reconnected.read()).data.customers.filter(c => c.slug === "sql-regression").length, 1);
console.log("Real isolated PostgreSQL: schema, seed preservation, persistence across connections and optimistic concurrency passed");
