import { workspaceCss as foundationCss } from './workspace-foundation-style.js';
import { loginCss } from './login-style.js';
import { statisticsCss } from './statistics-style.js';

export const workspaceCss = foundationCss + '\n' + statisticsCss + '\n' + loginCss + String.raw`
.registry-form{display:flex;flex-wrap:wrap;align-items:end;gap:14px;padding:20px 0;border-bottom:1px solid #dde5eb;margin-bottom:16px}
.registry-form label{display:block;font-size:14px;font-weight:600}
.registry-input{display:block;width:100%;padding:11px;border:1px solid #c8d5df;border-radius:7px;background:#fff;color:#172f3e;margin-top:6px}
.registry-form fieldset{border:1px solid #d5e1e8;border-radius:8px;padding:14px}
.registry-check{padding:5px}.registry-check input{margin-right:8px}
.registry-actions{display:flex;flex-wrap:wrap;gap:8px}
#registry-panel{margin-bottom:28px}#registry-panel .list-item{flex-wrap:wrap}#registry-panel .body{min-width:220px}
#registry-status{color:#125e51;font-weight:600}
.registry-overview{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:18px 0}.registry-overview div{padding:16px;border:1px solid #dbe5ea;border-radius:9px;background:#f8fafb}.registry-overview strong,.registry-overview span{display:block}.registry-overview strong{font-size:24px;color:#183746}.registry-overview span{margin-top:4px;font-size:11px;color:#6b808c}
.registry-customer{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:18px;align-items:center;padding:17px 0;border-bottom:1px solid #e3e9ed}.registry-customer-main{display:flex;align-items:flex-start;gap:13px;min-width:0}.registry-customer .body{display:grid;gap:4px;min-width:0}.registry-customer .body small{overflow-wrap:anywhere}.registry-swatch{display:flex;width:46px;height:46px;flex:none;overflow:hidden;border:1px solid #d5e1e7;border-radius:10px}.registry-swatch i{width:50%;height:100%}
.registry-editor-card{margin-top:22px;padding:22px;border:1px solid #bcd1d8;border-radius:12px;background:#f7fafb;box-shadow:0 12px 35px #17384a0c}.registry-editor-head{display:flex;align-items:flex-start;justify-content:space-between;gap:18px;padding-bottom:16px;border-bottom:1px solid #dce6ea}.registry-editor-head h3{margin:4px 0;font-size:22px}.registry-editor-head p{margin:0;color:#667d89}.registry-editor-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));align-items:start}.registry-editor-form h4,.registry-editor-form fieldset,.registry-editor-form>button,.registry-editor-form>.registry-color-row,.registry-editor-form>.registry-agent{grid-column:1/-1}.registry-editor-form h4{margin:0;font-size:15px}.registry-hint{display:block;margin-top:5px;color:#70848f;font-size:10px;font-weight:400;line-height:1.45}.registry-color-row{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.registry-color{height:44px;padding:5px}.registry-agent{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;background:#fff}.registry-agent legend{font-weight:700}.registry-agent>.registry-switch,.registry-agent>.registry-tools,.registry-agent>.registry-domain-note,.registry-agent>.registry-hint{grid-column:1/-1}.registry-switch{display:flex!important;align-items:center;gap:9px}.registry-switch input{width:18px;height:18px}.registry-range{padding:3px 0;border:0}.registry-tools{display:grid;gap:4px;padding-top:6px}.registry-domain-note{margin:0;padding:12px;border-radius:8px;background:#edf5f4;color:#315e5a;font-size:11px}.registry-create{background:#fbfcfd;padding-left:14px;padding-right:14px;border-radius:10px}
@media(max-width:850px){.registry-overview{grid-template-columns:repeat(2,minmax(0,1fr))}.registry-customer{grid-template-columns:1fr}.registry-editor-form,.registry-agent{grid-template-columns:1fr}.registry-editor-form h4,.registry-editor-form fieldset,.registry-editor-form>button,.registry-editor-form>.registry-color-row,.registry-editor-form>.registry-agent,.registry-agent>.registry-switch,.registry-agent>.registry-tools,.registry-agent>.registry-domain-note,.registry-agent>.registry-hint{grid-column:1}.registry-color-row{grid-template-columns:1fr 1fr}}
@media(max-width:520px){.registry-overview,.registry-color-row{grid-template-columns:1fr}.registry-actions .button,.registry-actions a{width:100%;justify-content:center}}
`;
